if [[ $- != *i* ]]; then return; fi
export BASH_PROFILE="$HOME/.bash_profile"

# check dotfiles repository
src_dir=$(dirname $(readlink -f $HOME/.bash_profile))
if [ ! -z "$(cd ${src_dir}; git status -s)" ]; then
  echo "you have something to do with dotfiles git repository"
fi

## add given path to PATH
source $HOME/.export_path
source $HOME/.export_envs
source $HOME/.ssh_profile

# machine specific profile
[ -f $HOME/.profile ] && source $HOME/.profile

if [ -f $HOME/.bashrc ] && [ "${BASHRC-undefined}" == "undefined" ]; then
  source $HOME/.bashrc
fi
