# login-matters
set -g default-shell "${SHELL}"
set-option -g default-command "${SHELL}"

# change prefix
set -g prefix C-t
unbind C-b

# config reload
bind r source-file ~/.tmux.conf \; display "config reloaded!"

# display and select pane
bind-key e display-panes

# like-vim
set-window-option -g mode-keys vi
bind s split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# my layout
bind 6 split-window -h \; split-window -h \; select-layout even-horizontal \; split-window -v \; select-pane -L \; split-window -v \; select-pane -L \; split-window -v \; select-pane -U
bind 8 split-window -h \; split-window -h \; split-window -h \; select-layout even-horizontal \; split-window -v \; select-pane -L \; split-window -v \; select-pane -L \; split-window -v \; select-pane -L \; split-window -v \; select-pane -U

# mouse
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"
bind -n WheelDownPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "send-keys -M"

# clipboard
set -s set-clipboard on

# 256-colors terminal
set -g default-terminal "xterm-256color"
set -g status-bg blue
set -g pane-active-border-style fg="blue"
set -sg escape-time 1

# tpm plugings
## List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# tmux-resurrect settings
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'ssh jupyter-notebook'

# tmux-continuum settings
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'